{"uid":"151e5b64c73a0be","name":"test_local_checkbox_interaction","fullName":"selenium_demoblaze_framework.tests.test_checkboxes.TestCheckboxes#test_local_checkbox_interaction","historyId":"db3c005a4eac1cce9b186e847a7379f9","time":{"start":1761243551201,"stop":1761243551201,"duration":0},"description":"This test verifies checkbox functionality by checking, unchecking, and asserting states on a locally-hosted, 100% reliable test page.","descriptionHtml":"<p>This test verifies checkbox functionality by checking, unchecking, and asserting states on a locally-hosted, 100% reliable test page.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56263ed3efba <unknown>\n#1 0x56263e7c36d0 <unknown>\n#2 0x56263e847e12 <unknown>\n#3 0x56263e846f9e <unknown>\n#4 0x56263e848b72 <unknown>\n#5 0x56263e848946 <unknown>\n#6 0x56263e83ac03 <unknown>\n#7 0x56263e8077a8 <unknown>\n#8 0x56263e808421 <unknown>\n#9 0x56263ed03b28 <unknown>\n#10 0x56263ed0787f <unknown>\n#11 0x56263ecebc49 <unknown>\n#12 0x56263ed08405 <unknown>\n#13 0x56263ecd14ff <unknown>\n#14 0x56263ed2c258 <unknown>\n#15 0x56263ed2c432 <unknown>\n#16 0x56263ed3dfa3 <unknown>\n#17 0x7f64b049caa4 <unknown>\n#18 0x7f64b0529c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55be060a5fba <unknown>\nE   #1 0x55be05b2a6d0 <unknown>\nE   #2 0x55be05baee12 <unknown>\nE   #3 0x55be05badf9e <unknown>\nE   #4 0x55be05bafb72 <unknown>\nE   #5 0x55be05baf946 <unknown>\nE   #6 0x55be05ba1c03 <unknown>\nE   #7 0x55be05b6e7a8 <unknown>\nE   #8 0x55be05b6f421 <unknown>\nE   #9 0x55be0606ab28 <unknown>\nE   #10 0x55be0606e87f <unknown>\nE   #11 0x55be06052c49 <unknown>\nE   #12 0x55be0606f405 <unknown>\nE   #13 0x55be060384ff <unknown>\nE   #14 0x55be06093258 <unknown>\nE   #15 0x55be06093432 <unknown>\nE   #16 0x55be060a4fa3 <unknown>\nE   #17 0x7f488569caa4 <unknown>\nE   #18 0x7f4885729c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_checkboxes.py:93: in setup_and_teardown\n    self.driver = self.browser_config.get_driver()\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56263ed3efba <unknown>\nE   #1 0x56263e7c36d0 <unknown>\nE   #2 0x56263e847e12 <unknown>\nE   #3 0x56263e846f9e <unknown>\nE   #4 0x56263e848b72 <unknown>\nE   #5 0x56263e848946 <unknown>\nE   #6 0x56263e83ac03 <unknown>\nE   #7 0x56263e8077a8 <unknown>\nE   #8 0x56263e808421 <unknown>\nE   #9 0x56263ed03b28 <unknown>\nE   #10 0x56263ed0787f <unknown>\nE   #11 0x56263ecebc49 <unknown>\nE   #12 0x56263ed08405 <unknown>\nE   #13 0x56263ecd14ff <unknown>\nE   #14 0x56263ed2c258 <unknown>\nE   #15 0x56263ed2c432 <unknown>\nE   #16 0x56263ed3dfa3 <unknown>\nE   #17 0x7f64b049caa4 <unknown>\nE   #18 0x7f64b0529c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551418,"duration":216},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551418,"stop":1761243551418,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551418,"stop":1761243551419,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243551419,"stop":1761243552570,"duration":1151},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56263ed3efba <unknown>\n#1 0x56263e7c36d0 <unknown>\n#2 0x56263e847e12 <unknown>\n#3 0x56263e846f9e <unknown>\n#4 0x56263e848b72 <unknown>\n#5 0x56263e848946 <unknown>\n#6 0x56263e83ac03 <unknown>\n#7 0x56263e8077a8 <unknown>\n#8 0x56263e808421 <unknown>\n#9 0x56263ed03b28 <unknown>\n#10 0x56263ed0787f <unknown>\n#11 0x56263ecebc49 <unknown>\n#12 0x56263ed08405 <unknown>\n#13 0x56263ecd14ff <unknown>\n#14 0x56263ed2c258 <unknown>\n#15 0x56263ed2c432 <unknown>\n#16 0x56263ed3dfa3 <unknown>\n#17 0x7f64b049caa4 <unknown>\n#18 0x7f64b0529c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_checkboxes.py\", line 93, in setup_and_teardown\n    self.driver = self.browser_config.get_driver()\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"This test verifies checkbox functionality by checking, unchecking, and asserting states on a locally-hosted, 100% reliable test page.","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56263ed3efba <unknown>\n#1 0x56263e7c36d0 <unknown>\n#2 0x56263e847e12 <unknown>\n#3 0x56263e846f9e <unknown>\n#4 0x56263e848b72 <unknown>\n#5 0x56263e848946 <unknown>\n#6 0x56263e83ac03 <unknown>\n#7 0x56263e8077a8 <unknown>\n#8 0x56263e808421 <unknown>\n#9 0x56263ed03b28 <unknown>\n#10 0x56263ed0787f <unknown>\n#11 0x56263ecebc49 <unknown>\n#12 0x56263ed08405 <unknown>\n#13 0x56263ecd14ff <unknown>\n#14 0x56263ed2c258 <unknown>\n#15 0x56263ed2c432 <unknown>\n#16 0x56263ed3dfa3 <unknown>\n#17 0x7f64b049caa4 <unknown>\n#18 0x7f64b0529c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x55be060a5fba <unknown>\nE   #1 0x55be05b2a6d0 <unknown>\nE   #2 0x55be05baee12 <unknown>\nE   #3 0x55be05badf9e <unknown>\nE   #4 0x55be05bafb72 <unknown>\nE   #5 0x55be05baf946 <unknown>\nE   #6 0x55be05ba1c03 <unknown>\nE   #7 0x55be05b6e7a8 <unknown>\nE   #8 0x55be05b6f421 <unknown>\nE   #9 0x55be0606ab28 <unknown>\nE   #10 0x55be0606e87f <unknown>\nE   #11 0x55be06052c49 <unknown>\nE   #12 0x55be0606f405 <unknown>\nE   #13 0x55be060384ff <unknown>\nE   #14 0x55be06093258 <unknown>\nE   #15 0x55be06093432 <unknown>\nE   #16 0x55be060a4fa3 <unknown>\nE   #17 0x7f488569caa4 <unknown>\nE   #18 0x7f4885729c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_checkboxes.py:93: in setup_and_teardown\n    self.driver = self.browser_config.get_driver()\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56263ed3efba <unknown>\nE   #1 0x56263e7c36d0 <unknown>\nE   #2 0x56263e847e12 <unknown>\nE   #3 0x56263e846f9e <unknown>\nE   #4 0x56263e848b72 <unknown>\nE   #5 0x56263e848946 <unknown>\nE   #6 0x56263e83ac03 <unknown>\nE   #7 0x56263e8077a8 <unknown>\nE   #8 0x56263e808421 <unknown>\nE   #9 0x56263ed03b28 <unknown>\nE   #10 0x56263ed0787f <unknown>\nE   #11 0x56263ecebc49 <unknown>\nE   #12 0x56263ed08405 <unknown>\nE   #13 0x56263ecd14ff <unknown>\nE   #14 0x56263ed2c258 <unknown>\nE   #15 0x56263ed2c432 <unknown>\nE   #16 0x56263ed3dfa3 <unknown>\nE   #17 0x7f64b049caa4 <unknown>\nE   #18 0x7f64b0529c6c <unknown>","steps":[],"attachments":[{"uid":"41b29ab7c76ab3c3","name":"log","source":"41b29ab7c76ab3c3.txt","type":"text/plain","size":12766},{"uid":"bb987baa3dd00751","name":"stdout","source":"bb987baa3dd00751.txt","type":"text/plain","size":865},{"uid":"1bb11e992f9f461d","name":"stderr","source":"1bb11e992f9f461d.txt","type":"text/plain","size":451}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555323,"stop":1761243555323,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"story","value":"Test Checkbox States on a Local HTML Page"},{"name":"feature","value":"Form Elements"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_checkboxes"},{"name":"subSuite","value":"TestCheckboxes"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3434-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_checkboxes"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"6711ba4c9e814a02","status":"passed","time":{"start":1761243529458,"stop":1761243530857,"duration":1399}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":4,"unknown":0,"total":6},"items":[{"uid":"2bd72775b332129c","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/2bd72775b332129c","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243136599,"stop":1761243136599,"duration":0}},{"uid":"584ed6f364783132","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/3//#testresult/584ed6f364783132","status":"passed","time":{"start":1761242184667,"stop":1761242185947,"duration":1280}},{"uid":"5a7782d965e88ce5","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/2//#testresult/5a7782d965e88ce5","status":"passed","time":{"start":1761241752273,"stop":1761241753519,"duration":1246}},{"uid":"7379826167406314","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/3//#testresult/7379826167406314","status":"passed","time":{"start":1761241755150,"stop":1761241756600,"duration":1450}},{"uid":"5f7d2cf36dcba29f","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/1//#testresult/5f7d2cf36dcba29f","status":"passed","time":{"start":1761237949949,"stop":1761237950799,"duration":850}}]},"tags":[]},"source":"151e5b64c73a0be.json","parameterValues":[]}