{"uid":"48da199b63e3f118","name":"test_10_data_driven_excel[edge]","fullName":"selenium_demoblaze_framework.tests.test_demoblaze_e2e.TestDemoBlazeE2E#test_10_data_driven_excel","historyId":"b9ec2a2e06b2e6756a5e83fead27c8c1","time":{"start":1761243554121,"stop":1761243554121,"duration":0},"description":"\n        MODIFIED: Test now reads data from data/test_data.xlsx and performs UI actions.\n        ","descriptionHtml":"<pre><code>    MODIFIED: Test now reads data from data/test_data.xlsx and performs UI actions.\n</code></pre>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56482a4a2fba <unknown>\n#1 0x564829f276d0 <unknown>\n#2 0x564829fabe12 <unknown>\n#3 0x564829faaf9e <unknown>\n#4 0x564829facb72 <unknown>\n#5 0x564829fac946 <unknown>\n#6 0x564829f9ec03 <unknown>\n#7 0x564829f6b7a8 <unknown>\n#8 0x564829f6c421 <unknown>\n#9 0x56482a467b28 <unknown>\n#10 0x56482a46b87f <unknown>\n#11 0x56482a44fc49 <unknown>\n#12 0x56482a46c405 <unknown>\n#13 0x56482a4354ff <unknown>\n#14 0x56482a490258 <unknown>\n#15 0x56482a490432 <unknown>\n#16 0x56482a4a1fa3 <unknown>\n#17 0x7f4b2649caa4 <unknown>\n#18 0x7f4b26529c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x564927adefba <unknown>\nE   #1 0x5649275636d0 <unknown>\nE   #2 0x5649275e7e12 <unknown>\nE   #3 0x5649275e6f9e <unknown>\nE   #4 0x5649275e8b72 <unknown>\nE   #5 0x5649275e8946 <unknown>\nE   #6 0x5649275dac03 <unknown>\nE   #7 0x5649275a77a8 <unknown>\nE   #8 0x5649275a8421 <unknown>\nE   #9 0x564927aa3b28 <unknown>\nE   #10 0x564927aa787f <unknown>\nE   #11 0x564927a8bc49 <unknown>\nE   #12 0x564927aa8405 <unknown>\nE   #13 0x564927a714ff <unknown>\nE   #14 0x564927acc258 <unknown>\nE   #15 0x564927acc432 <unknown>\nE   #16 0x564927addfa3 <unknown>\nE   #17 0x7fa16549caa4 <unknown>\nE   #18 0x7fa165529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56482a4a2fba <unknown>\nE   #1 0x564829f276d0 <unknown>\nE   #2 0x564829fabe12 <unknown>\nE   #3 0x564829faaf9e <unknown>\nE   #4 0x564829facb72 <unknown>\nE   #5 0x564829fac946 <unknown>\nE   #6 0x564829f9ec03 <unknown>\nE   #7 0x564829f6b7a8 <unknown>\nE   #8 0x564829f6c421 <unknown>\nE   #9 0x56482a467b28 <unknown>\nE   #10 0x56482a46b87f <unknown>\nE   #11 0x56482a44fc49 <unknown>\nE   #12 0x56482a46c405 <unknown>\nE   #13 0x56482a4354ff <unknown>\nE   #14 0x56482a490258 <unknown>\nE   #15 0x56482a490432 <unknown>\nE   #16 0x56482a4a1fa3 <unknown>\nE   #17 0x7f4b2649caa4 <unknown>\nE   #18 0x7f4b26529c6c <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1761243551202,"stop":1761243551416,"duration":214},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243551417,"stop":1761243551417,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243554122,"stop":1761243555238,"duration":1116},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56482a4a2fba <unknown>\n#1 0x564829f276d0 <unknown>\n#2 0x564829fabe12 <unknown>\n#3 0x564829faaf9e <unknown>\n#4 0x564829facb72 <unknown>\n#5 0x564829fac946 <unknown>\n#6 0x564829f9ec03 <unknown>\n#7 0x564829f6b7a8 <unknown>\n#8 0x564829f6c421 <unknown>\n#9 0x56482a467b28 <unknown>\n#10 0x56482a46b87f <unknown>\n#11 0x56482a44fc49 <unknown>\n#12 0x56482a46c405 <unknown>\n#13 0x56482a4354ff <unknown>\n#14 0x56482a490258 <unknown>\n#15 0x56482a490432 <unknown>\n#16 0x56482a4a1fa3 <unknown>\n#17 0x7f4b2649caa4 <unknown>\n#18 0x7f4b26529c6c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_demoblaze_e2e.py\", line 1147, in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 207, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"\n        MODIFIED: Test now reads data from data/test_data.xlsx and performs UI actions.\n        ","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nStacktrace:\n#0 0x56482a4a2fba <unknown>\n#1 0x564829f276d0 <unknown>\n#2 0x564829fabe12 <unknown>\n#3 0x564829faaf9e <unknown>\n#4 0x564829facb72 <unknown>\n#5 0x564829fac946 <unknown>\n#6 0x564829f9ec03 <unknown>\n#7 0x564829f6b7a8 <unknown>\n#8 0x564829f6c421 <unknown>\n#9 0x56482a467b28 <unknown>\n#10 0x56482a46b87f <unknown>\n#11 0x56482a44fc49 <unknown>\n#12 0x56482a46c405 <unknown>\n#13 0x56482a4354ff <unknown>\n#14 0x56482a490258 <unknown>\n#15 0x56482a490432 <unknown>\n#16 0x56482a4a1fa3 <unknown>\n#17 0x7f4b2649caa4 <unknown>\n#18 0x7f4b26529c6c <unknown>","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x564927adefba <unknown>\nE   #1 0x5649275636d0 <unknown>\nE   #2 0x5649275e7e12 <unknown>\nE   #3 0x5649275e6f9e <unknown>\nE   #4 0x5649275e8b72 <unknown>\nE   #5 0x5649275e8946 <unknown>\nE   #6 0x5649275dac03 <unknown>\nE   #7 0x5649275a77a8 <unknown>\nE   #8 0x5649275a8421 <unknown>\nE   #9 0x564927aa3b28 <unknown>\nE   #10 0x564927aa787f <unknown>\nE   #11 0x564927a8bc49 <unknown>\nE   #12 0x564927aa8405 <unknown>\nE   #13 0x564927a714ff <unknown>\nE   #14 0x564927acc258 <unknown>\nE   #15 0x564927acc432 <unknown>\nE   #16 0x564927addfa3 <unknown>\nE   #17 0x7fa16549caa4 <unknown>\nE   #18 0x7fa165529c6c <unknown>\n\nDuring handling of the above exception, another exception occurred:\nselenium_demoblaze_framework/tests/test_demoblaze_e2e.py:1147: in setup_and_teardown\n    self.driver = self.browser_config.get_driver(browser_name)\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:207: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:291: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:346: in execute\n    self.error_handler.check_response(response)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response\n    raise exception_class(message, screen, stacktrace)\nE   selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found\nE   Stacktrace:\nE   #0 0x56482a4a2fba <unknown>\nE   #1 0x564829f276d0 <unknown>\nE   #2 0x564829fabe12 <unknown>\nE   #3 0x564829faaf9e <unknown>\nE   #4 0x564829facb72 <unknown>\nE   #5 0x564829fac946 <unknown>\nE   #6 0x564829f9ec03 <unknown>\nE   #7 0x564829f6b7a8 <unknown>\nE   #8 0x564829f6c421 <unknown>\nE   #9 0x56482a467b28 <unknown>\nE   #10 0x56482a46b87f <unknown>\nE   #11 0x56482a44fc49 <unknown>\nE   #12 0x56482a46c405 <unknown>\nE   #13 0x56482a4354ff <unknown>\nE   #14 0x56482a490258 <unknown>\nE   #15 0x56482a490432 <unknown>\nE   #16 0x56482a4a1fa3 <unknown>\nE   #17 0x7f4b2649caa4 <unknown>\nE   #18 0x7f4b26529c6c <unknown>","steps":[],"attachments":[{"uid":"77966e0ecc94e850","name":"log","source":"77966e0ecc94e850.txt","type":"text/plain","size":7699},{"uid":"b9ed21e958a12400","name":"stdout","source":"b9ed21e958a12400.txt","type":"text/plain","size":863},{"uid":"aec6e4f17b36096a","name":"stderr","source":"aec6e4f17b36096a.txt","type":"text/plain","size":225}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243555434,"stop":1761243555434,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Data Driven Testing"},{"name":"story","value":"Test with Excel Data"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_demoblaze_e2e"},{"name":"subSuite","value":"TestDemoBlazeE2E"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3443-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_demoblaze_e2e"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser_name","value":"'edge'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"375279266c1bc36b","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/5//#testresult/375279266c1bc36b","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","time":{"start":1761243137238,"stop":1761243137238,"duration":0}}]},"tags":[]},"source":"48da199b63e3f118.json","parameterValues":["'edge'"]}