{"uid":"2bd72775b332129c","name":"test_local_checkbox_interaction","fullName":"selenium_demoblaze_framework.tests.test_checkboxes.TestCheckboxes#test_local_checkbox_interaction","historyId":"db3c005a4eac1cce9b186e847a7379f9","time":{"start":1761243136599,"stop":1761243136599,"duration":0},"description":"This test verifies checkbox functionality by checking, unchecking, and asserting states on a locally-hosted, 100% reliable test page.","descriptionHtml":"<p>This test verifies checkbox functionality by checking, unchecking, and asserting states on a locally-hosted, 100% reliable test page.</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:51: in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py:44: in get_path\n    raise NoSuchDriverException(f\"Unable to locate or obtain driver for {options.capabilities['browserName']}\")\nE   selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for MicrosoftEdge; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\nDuring handling of the above exception, another exception occurred:\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py:38: in get_path\n    path = SeleniumManager().driver_location(options) if path is None else path\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py:94: in driver_location\n    output = self.run(args)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py:140: in run\n    raise WebDriverException(f\"Unsuccessful command executed: {command}.\\n{result}{stderr}\")\nE   selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager --browser MicrosoftEdge --debug --output json.\nE   {'code': 65, 'message': 'error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_141_LINUX): error trying to connect: dns error: failed to lookup address information: Name does not resolve', 'driver_path': '', 'browser_path': ''}\n\nThe above exception was the direct cause of the following exception:\nselenium_demoblaze_framework/tests/test_checkboxes.py:93: in setup_and_teardown\n    self.driver = self.browser_config.get_driver()\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:51: in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py:41: in get_path\n    raise NoSuchDriverException(msg) from err\nE   selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"_session_faker","time":{"start":1761243136601,"stop":1761243136774,"duration":173},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"session_browser","time":{"start":1761243136774,"stop":1761243136774,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"set_browser_env","time":{"start":1761243136774,"stop":1761243136775,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_and_teardown","time":{"start":1761243136775,"stop":1761243136847,"duration":72},"status":"broken","statusMessage":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/tests/test_checkboxes.py\", line 93, in setup_and_teardown\n    self.driver = self.browser_config.get_driver()\n  File \"/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/selenium_demoblaze_framework/config/browser_config.py\", line 191, in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py\", line 51, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n  File \"/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py\", line 41, in get_path\n    raise NoSuchDriverException(msg) from err\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"description":"This test verifies checkbox functionality by checking, unchecking, and asserting states on a locally-hosted, 100% reliable test page.","status":"broken","statusMessage":"selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","statusTrace":"selenium_demoblaze_framework/config/browser_config.py:185: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:51: in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py:44: in get_path\n    raise NoSuchDriverException(f\"Unable to locate or obtain driver for {options.capabilities['browserName']}\")\nE   selenium.common.exceptions.NoSuchDriverException: Message: Unable to locate or obtain driver for MicrosoftEdge; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\nDuring handling of the above exception, another exception occurred:\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py:38: in get_path\n    path = SeleniumManager().driver_location(options) if path is None else path\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py:94: in driver_location\n    output = self.run(args)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/selenium_manager.py:140: in run\n    raise WebDriverException(f\"Unsuccessful command executed: {command}.\\n{result}{stderr}\")\nE   selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: /opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager --browser MicrosoftEdge --debug --output json.\nE   {'code': 65, 'message': 'error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_141_LINUX): error trying to connect: dns error: failed to lookup address information: Name does not resolve', 'driver_path': '', 'browser_path': ''}\n\nThe above exception was the direct cause of the following exception:\nselenium_demoblaze_framework/tests/test_checkboxes.py:93: in setup_and_teardown\n    self.driver = self.browser_config.get_driver()\nselenium_demoblaze_framework/config/browser_config.py:191: in get_driver\n    driver = webdriver.Edge(service=service, options=self.get_edge_options())\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/edge/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py:51: in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/driver_finder.py:41: in get_path\n    raise NoSuchDriverException(msg) from err\nE   selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for MicrosoftEdge using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location","steps":[],"attachments":[{"uid":"8e34cf9f50db2082","name":"log","source":"8e34cf9f50db2082.txt","type":"text/plain","size":6509},{"uid":"5d27516b096af9b","name":"stdout","source":"5d27516b096af9b.txt","type":"text/plain","size":448},{"uid":"4868d276baf1283c","name":"stderr","source":"4868d276baf1283c.txt","type":"text/plain","size":451}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":3,"hasContent":true},"afterStages":[{"name":"set_browser_env::0","time":{"start":1761243137349,"stop":1761243137349,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"feature","value":"Form Elements"},{"name":"story","value":"Test Checkbox States on a Local HTML Page"},{"name":"parentSuite","value":"selenium_demoblaze_framework.tests"},{"name":"suite","value":"test_checkboxes"},{"name":"subSuite","value":"TestCheckboxes"},{"name":"host","value":"runnervmwhb2z"},{"name":"thread","value":"3533-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"selenium_demoblaze_framework.tests.test_checkboxes"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"b319e3bcb1797e80","status":"passed","time":{"start":1761243119625,"stop":1761243121186,"duration":1561}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":4,"unknown":0,"total":5},"items":[{"uid":"584ed6f364783132","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/3//#testresult/584ed6f364783132","status":"passed","time":{"start":1761242184667,"stop":1761242185947,"duration":1280}},{"uid":"5a7782d965e88ce5","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/2//#testresult/5a7782d965e88ce5","status":"passed","time":{"start":1761241752273,"stop":1761241753519,"duration":1246}},{"uid":"7379826167406314","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/3//#testresult/7379826167406314","status":"passed","time":{"start":1761241755150,"stop":1761241756600,"duration":1450}},{"uid":"5f7d2cf36dcba29f","reportUrl":"https://Roykunaljit.github.io/selenium-demoblaze-operations/1//#testresult/5f7d2cf36dcba29f","status":"passed","time":{"start":1761237949949,"stop":1761237950799,"duration":850}}]},"tags":[]},"source":"2bd72775b332129c.json","parameterValues":[]}