DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.address`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.address` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.automotive`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.automotive` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.bank`.
DEBUG    faker.factory:factory.py:86 Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.barcode`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.barcode` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.color`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.color` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.company`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.company` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.credit_card`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.credit_card` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.currency`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.currency` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.date_time`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.date_time` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.geo`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.geo` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.internet`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.internet` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.job`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.job` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.lorem`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.lorem` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.misc`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.misc` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.passport`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.passport` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.person`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.person` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.phone_number`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.phone_number` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
DEBUG    faker.factory:factory.py:76 Looking for locale `en_US` in provider `faker.providers.ssn`.
DEBUG    faker.factory:factory.py:95 Provider `faker.providers.ssn` has been localized to `en_US`.
DEBUG    faker.factory:factory.py:106 Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
INFO     TestCheckboxes:test_checkboxes.py:43 ==================================================
INFO     TestCheckboxes:test_checkboxes.py:44 Starting new LOCAL Checkbox Test
INFO     TestCheckboxes:test_checkboxes.py:86 Local test server running at: http://localhost:43835/checkbox_test.html
INFO     TestCheckboxes:test_checkboxes.py:91 Initializing browser: edge
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:63 Selenium Manager binary found at: /opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:120 Executing process: /opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/selenium/webdriver/common/linux/selenium-manager --browser MicrosoftEdge --debug --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Found msedgedriver 140.0.3485.94 in PATH: /usr/bin/msedgedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 MicrosoftEdge detected at /usr/bin/microsoft-edge
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Running command: /usr/bin/microsoft-edge --version
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Output: "Microsoft Edge 141.0.3537.92 "
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Detected browser: MicrosoftEdge 141.0.3537.92
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Reading msedgedriver version from https://msedgedriver.azureedge.net/LATEST_RELEASE_141_LINUX
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:135 Exception managing MicrosoftEdge: error sending request for url (https://msedgedriver.azureedge.net/LATEST_RELEASE_141_LINUX): error trying to connect: dns error: failed to lookup address information: Name does not resolve
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:135 The msedgedriver version (140.0.3485.94) detected in PATH at /usr/bin/msedgedriver might not be compatible with the detected MicrosoftEdge version (141.0.3537.92); currently, msedgedriver  is recommended for MicrosoftEdge 141.*, so it is advised to delete the driver in PATH and retry
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Driver path: /usr/bin/msedgedriver
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:137 Browser path: /usr/bin/microsoft-edge
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:98 Using driver at: /usr/bin/msedgedriver
DEBUG    selenium.webdriver.common.service:service.py:215 Started executable: `/usr/bin/msedgedriver` in a child process with pid: 3600
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:52043/session {"capabilities": {"firstMatch": [{}], "alwaysMatch": {"browserName": "MicrosoftEdge", "pageLoadStrategy": "normal", "browserVersion": null, "ms:edgeOptions": {"prefs": {"download.default_directory": "/home/runner/work/selenium-demoblaze-operations/selenium-demoblaze-operations/downloads", "download.prompt_for_download": false, "download.directory_upgrade": true, "safebrowsing.enabled": false, "profile.default_content_settings.popups": 0, "profile.default_content_setting_values.notifications": 2}, "excludeSwitches": ["enable-logging", "enable-automation"], "useAutomationExtension": false, "extensions": [], "binary": "/usr/bin/microsoft-edge", "args": ["--headless=new", "--window-size=1920,1080", "--start-maximized", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-software-rasterizer", "--disable-blink-features=AutomationControlled", "--remote-debugging-port=9222", "--disable-extensions", "--disable-popup-blocking", "--ignore-certificate-errors"]}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:52043
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52043 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"MicrosoftEdge","browserVersion":"141.0.3537.92","fedcm:accounts":true,"ms:edgeOptions":{"debuggerAddress":"localhost:9222"},"msedge":{"msedgedriverVersion":"140.0.3485.94 (9831641b47fbddfcc786ceb18c2e499530dc5e2b)","userDataDir":"/tmp/.com.microsoft.Edge.n3bKYB"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"linux","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"e52dbca3fd8ab21bd4e24a48ee1b629c"}} | headers=HTTPHeaderDict({'Content-Length': '816', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:52043/session/e52dbca3fd8ab21bd4e24a48ee1b629c/timeouts {"implicit": 10000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52043 "POST /session/e52dbca3fd8ab21bd4e24a48ee1b629c/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:52043/session/e52dbca3fd8ab21bd4e24a48ee1b629c/timeouts {"pageLoad": 60000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52043 "POST /session/e52dbca3fd8ab21bd4e24a48ee1b629c/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
INFO     TestCheckboxes:test_checkboxes.py:112 Navigating to local checkbox page: http://localhost:43835/checkbox_test.html
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 POST http://localhost:52043/session/e52dbca3fd8ab21bd4e24a48ee1b629c/url {"url": "http://localhost:43835/checkbox_test.html"}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52043 "POST /session/e52dbca3fd8ab21bd4e24a48ee1b629c/url HTTP/1.1" 404 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=404 | data={"value":{"error":"invalid session id","message":"invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: Unable to receive message from renderer\n  (Session info: MicrosoftEdge=141.0.3537.92)","stacktrace":"#0 0x5565cbe02cce \u003Cunknown>\n#1 0x5565cb88c656 \u003Cunknown>\n#2 0x5565cb875e55 \u003Cunknown>\n#3 0x5565cb875c02 \u003Cunknown>\n#4 0x5565cb87405c \u003Cunknown>\n#5 0x5565cb874357 \u003Cunknown>\n#6 0x5565cb88fe63 \u003Cunknown>\n#7 0x5565cb92375e \u003Cunknown>\n#8 0x5565cb902802 \u003Cunknown>\n#9 0x5565cb92300c \u003Cunknown>\n#10 0x5565cb9025d3 \u003Cunknown>\n#11 0x5565cb8d0228 \u003Cunknown>\n#12 0x5565cb8d0e11 \u003Cunknown>\n#13 0x5565cbdd216e \u003Cunknown>\n#14 0x5565cbdd52cb \u003Cunknown>\n#15 0x5565cbdd4d2b \u003Cunknown>\n#16 0x5565cbdd5785 \u003Cunknown>\n#17 0x5565cbdbf4e3 \u003Cunknown>\n#18 0x5565cbdd5b52 \u003Cunknown>\n#19 0x5565cbda9242 \u003Cunknown>\n#20 0x5565cbdf1078 \u003Cunknown>\n#21 0x5565cbdf129c \u003Cunknown>\n#22 0x5565cbe01b59 \u003Cunknown>\n#23 0x7f1eafe9caa4 \u003Cunknown>\n#24 0x7f1eaff29c6c \u003Cunknown>\n"}} | headers=HTTPHeaderDict({'Content-Length': '1117', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request
INFO     TestCheckboxes:test_checkboxes.py:99 Checkbox Test completed
INFO     TestCheckboxes:test_checkboxes.py:100 ==================================================
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:313 DELETE http://localhost:52043/session/e52dbca3fd8ab21bd4e24a48ee1b629c {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:52043 "DELETE /session/e52dbca3fd8ab21bd4e24a48ee1b629c HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:329 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:356 Finished Request